---
title: "Proposing ideas to improve quality of starting rotation: Los Angeles Angels' version"
author: "Ian Kwon"
date: "12/4/2019"
output: html_document
---

```{r}
# Required packages to start
library(dplyr)
library(ggplot2)
library(data.table)
```
### Intro

```{r}
#A pro sports teams’ goal should be to win a championship. In Major League Baseball (MLB) to have a chance at the championship trophy, teams first need to do well in the 'regular season' and make it into 'playoffs'. Teams believe that star players, especially good pitchers, can bring the advantage. To check if the following belief of whether good starting pitching will get a team close to a championship, we take unique yet diverse approaches for solution. 

```

#Data Access
```{r}
#reading data
pitchers <- fread("C:/Users/iankw/Documents/Junior/Stat 184/Stat184-Final-Project/Finalprojectdataset.csv")
salary <- fread("C:/Users/iankw/Documents/Junior/Stat 184/Stat184-Final-Project/Salary.csv")


#inspecting data
str(pitchers)
str(salary)
names(pitchers)
names(salary)
View(pitchers)
View(salary)
#Salary data has 15 more variables compared to Data 1.The datasets seem to have some same names, some different names and some similar names too. It seems like we can later join later with the PlayerID number if necessary. 
```
# Intro
```{r}
#In order to win such championships, big market teams like the Boston Red Sox pay big name starting pitchers like David Price for 30 million dollars a year. However small market teams like the Oakland Athletics pay not so famous pitchers like Brett Anderson for almost the tenth of what Price is paid annually.


priceanderson <-
  salary%>%
  select(Player,Year, Team,Payrollsalary)%>%
  filter(Player == "David Price" |Player == "Brett Anderson")
priceanderson

# Price had guaranteed 30 million dollars the past 3 years while Anderson had only guaranteed himself 4 million dollars in 2018.

priceanderson2018<- 
  priceanderson%>%
  filter(Year == "2018")%>%
  ggplot(aes(x= Player, y= Payrollsalary ))+
  ylab("Payroll Salary ($)")+
  geom_bar(stat= "identity" )

priceanderson2018

# Comparing only the year when both the pitchers were paid (2018), the bar graph gives us how drastic the difference in salary it is for these two pitchers. 

```

```{r}
#It must be the team's financial status that limits teams like Oakland to what they can pay. Let's check. The Oakland Athletics managed to pay the whole team about 80.315 million dollars in 2018 according to Spotrac. If the Athletics were to pay David Price his salary, let's see how much percentage of the salary David Price would have eaten up. 

salarypercent <- function(oakland) {
  diffsalary <- (oakland / 80315000)
  return(diffsalary)
}
salarypercent(30000000)

#David Price would have eaten up about 37.35% of the team's salary. Let's check how much salary percentage Brett Anderson cost.
```

```{r}
salarypercent(4000000)

#Brett Anderson had only eaten up 4% of the team's salary yet was the highest paid pitcher on the team. Baseball seems to have major differences when it comes to the ability of spending money per teams. Unfortunately, these differences lead to different results as well. The Boston Red Sox won the 2018 World Series championship in 2018 with pitchers like David Price. Hence, we may want to check how approximately starting pitchers are paid and later check which pitchers for how much price, would teams want to acquire as well.  

```


#The data
```{r}
# Now that we understand how diversify the pay is within MLB pitchers, we want to dig deeper at the pitching staff of MLB teams from 2016-2018 and get a better approximate of how MLB starting pitchers are getting paid. 

# Good idea to start things off would be to select the assumed 'needed variables' for each dataset. We want to know the 'players', 'PlayerID' to join 2 tables, the 'team' of the players, respective years, 'GS' (= Games Started) to know whether the pitcher was healthy, 'ERA' (= Earned Run Average) to evaluate how good the pitcher is in preventing runs, 'ProjectedFull' ( to get an approximate of how many wins a pitcher can contribute to the team) and 'Playoff' (to note whether the team of the player made the playoffs or not.)

pitchers2<-
  pitchers%>%
  select(Player,PlayerID,Team, Year,GS,ERA,ProjectedFull,Playoff)
pitchers2

#Similarly, we want the following variables for the salary dataset. 'PlayerID' to join the two tables, 'Payrollsalary' to understand how much the player got paid and 'Payrollpercentage' in case we wonder how much percentage the player was eating up compared to the total payroll. 

salary2<-
  salary%>%
  select(PlayerID,Payrollsalary,Payrollpercentage)
salary2

# joined table
pitchersalary<- 
  pitchers2%>%
  left_join(salary2, by =c("PlayerID" = "PlayerID"))

str(pitchersalary)
View(pitchersalary)

# The last column, Payrollpercentage has the % signal next to all its numbers so it may be a good idea to get rid of that for computations later on. 

pitchersalary<-
  pitchersalary %>% 
  mutate(Payrollpercentage = gsub(pattern = "[,%]", replacement = "", Payrollpercentage))
pitchersalary

# Now we have a clean data table with the variables we want to use and where there is no percentage sign when if computing later of the last variable. 
```

# How do playoff teams differ from non-playoff teams?
```{r}
# Let's take a look at how teams who have made it into the playoffs had paid their starting rotation. We want to see if the following belief 1) Do Playoff teams have better quality pitchers? is satisfied. If it is so, it would make sense that better quality pitchers are wanted for teams to make playoffs. 

playoff<-
  pitchersalary%>%
  group_by(Playoff, Year)%>%
  summarise(avg = mean(ProjectedFull))%>%
  ggplot(aes(x = Year, y = avg))+
  ylab("Average Projected Wins per starting pitcher")+
  geom_line(aes(color = "red"), show.legend = FALSE)+
  theme(axis.text.x = element_text(angle = 30, hjust=1))+
  facet_wrap(~Playoff)

playoff

#It comes to no surprise that the facet '1', which is teams that had made playoffs, had more pitchers with higher average of 'ProjectedFull' (=Average Projected Wins per starting pitcher). Teams that did not make the playoffs or teams that had just barely made the playoffs as a wildcard team were respectively facets '0' and '2'. Facet 2: the wildcard teams had the next better quality starting pitchers and facet 0 had the worst out of the three. Not surprisingly, the quality of starting pitchers in the rotation mattered on whether teams make into the playoffs or not, including wildcard teams. Teams would hence want to consider the quality of pitchers when carefully assessing and acquiring starting pitchers. 

```


```{r}
# With the pitchersalary data we have, we can do investigations on the baseball statistics as well as the salary of the starting pitchers from 2016 to 2018. I am interested in how my favorite baseball team: Los Angeles Angels have spent on starting pitchers the past 3 years.

angelspitchers<- 
  pitchersalary%>%
  filter(Team == "LAA" )%>%
  group_by(Player, Payrollsalary, Year )%>%
  ggplot(aes(x= reorder(Player,desc(Payrollsalary)), y= Payrollsalary))+
  xlab("Player")+
  ylab("Payroll Salary ($)")+
  geom_point(aes())+
  theme(axis.text.x = element_text(angle = 30, hjust=1))

angelspitchers

# We can see that Jered Weaver was the highest paid starting pitcher (at around 20 million dollars) in the past 3 years. We can also see that there has only been 2 pitchers who had stayed in the rotation for more than one year(Matt Shoemaker and Tyler Skaggs), and every other pitchers have only been in the rotation for a year. The Angels clearly need pitchers who can pitch in the rotation for consecutive years (a healthy pitcher).

#We can wonder whether at least the money was being spent wisely. Which leads to the next question: how well did Jered Weaver play when he was paid that much money? 
```


```{r}
jeredweaver<-
  pitchersalary%>%
  filter(Player == "Jered Weaver")%>%
  summarise( median = median(ERA), mean = mean(ERA))
  
jeredweaver

# JeredWeaver had a ERA of 5.06. Casual baseball fans would realize right away that a pitcher with an ERA of 5.06 is a very bad starting pitcher. However, since some may know so, we will compare Weaver's ERA to the league average back in 2016 when he posted such ERA.

```

```{r}
leagueaverage<-
  pitchersalary%>%
  summarise( median = median(ERA), mean = mean(ERA))

leagueaverage

# Take a look at the median and mean of all 501 starting pitcher data we have. They post a median and mean at about 4.3, which is a lower ERA number compared to Weaver's 5.06. The league average pitcher will post better numbers than Weaver, yet the Angels paid Weaver 20 million dollars and still got worse pitching than league average. 


```

```{r}
# Instead of giving Jered Weaver such amount of money, what would have happened if the Angels paid 2 pitchers for 20 million dollars? 

jeredweaver2<-
  pitchersalary%>%
  filter(Player == "Jered Weaver")%>%
  summarise(ERAavg = mean(ERA), totalwins = sum(ProjectedFull))
  
jeredweaver2

tenmillionplayers<-
  pitchersalary%>%
  filter(Payrollsalary == 10000000 & GS >26)
tenmillionplayers

tenmillion<-
  tenmillionplayers%>%
  summarise(ERAavg = mean(ERA), totalwins = sum(ProjectedFull))

tenmillion


#For simplicity sakes, we look at two pitchers who were paid 10 million dollars and also healthy to start more than 26 games that season. Andrew Cashner and J.A Happ meet the standards and have both produced a ERA below 3.5 and ProjectedFull of 38.6 together. Basically, for the same amount of money, the Angels could have recorded 24.9 more team wins for the same money.

```

```{r}
# We figured that the Angels have not spent money wisely on that one big money pitcher Jered Weaver at 20 million dollars but yet already came up with alternatives that could have been better for the team. Now that we figured out how to efficiently spend that big 20 million dollars, let's see if the Angels had spent enough money compared to other teams.  

SummaryStats <- 
  pitchersalary %>%
  group_by(Team)%>%
  summarise(avg = mean(Payrollsalary),
            se = sd(Payrollsalary) / sqrt(n()))%>%
  mutate(top = avg + 2 * se,
         bottom = avg - 2 * se)


SummaryStats %>%
  ggplot(aes(x = reorder(Team, desc(avg)), y = avg)) +
  ylab("Average Payroll Salary ($)")+
  geom_bar(stat = "identity", alpha=0.2, aes(fill = "red"), show.legend = FALSE) +
  geom_errorbar(aes(x = Team, 
                    ymax = top, 
                    ymin = bottom), width=0.5) +
  theme(axis.text.x = element_text(angle = 30, hjust=1))

#The Los Angeles Angels (LAA) are ranked 18th out of 30 teams in the average spend of money of starting pitchers. As we noticed from the earlier 'angelspitchers' dotplot, there is quite a fluctuation in the range of money they spend as well according to the errorbar. For example, Cleveland (CLE) spend more on average payroll salary but yet error bar suggests they have more of a condensed range of money spent on their pitchers.

```

```{r}
# As we had checked the boxplots above, let's check if the Angels and the Indians have made the playoffs in the past 3 years. Since they had spent similar amount of money into their starting pitching, we might assume that they had similar team results as well. 

laacle<-
  pitchersalary%>%
  group_by(Year, Playoff)%>%
  filter(Team == "CLE" | Team == "LAA")%>%
  ggplot(aes(x = Team, y = Playoff))+
  ylab("Made Playoffs")+
  geom_point()+
  theme(axis.text.x = element_text(angle = 30, hjust=1))+
  facet_wrap(~Year)
laacle

#Since 1 is making playoffs and 0 is not making playoffs, we know CLE has made the playoffs during 2016 -2018 while LAA has not. 

#While spending on starting pitchers were relatively same for CLE and LAA, CLE made the playoffs all the time from 2016 to 2018 while LAA had not made so. It may be the Angels were not spending enough money and also not spending their money wisely. Or, it also may be that Cleveland are condensing their salary to a few better quality pitchers in a wise manner while the Angels are diversifying their salary to a lot of not quality pitchers. 
```

```{r}
# Now that we understand the Angels have not been spending enough money and also not been spending money wisely, we know what to tell the Angels' baseball operation staff to do: spend more money and wisely on starting pitchers! In the game of baseball, it is somewhat inevitable to spend more money in order to make the playoffs and win a championship. Let's assume the Angels have 50 million dollars to spend on a 5 man rotation so basically 10 million dollars to spend on each starting pitcher. Also, they want healthy pitchers who can pitch more than 26 games and good pitchers who can pitch under a ERA of 4

finalrotation<-
  pitchersalary%>%
  filter(Payrollsalary <= 10000000 & GS >26 & ERA <4 & Year == 2016)

finalrotation

require(data.table)
d <- data.table(finalrotation, key="ERA")
d[, head(.SD), by=Payrollsalary]

nrow(d)

# In 2016, the Angels could have spent money on 22 different pitchers.We list the name of vectors and make the function randomly choose 5 pitchers for us. 

e<-d%>%
  select("PlayerID")
e

e<- as.character(e)
target

```

```{r}
finalrotation%>%
  filter(PlayerID %in% e)
  summarise(salary = sum(Payrollsalary), ERA = mean(ERA), Wins = sum(ProjectedFull))
finalrotation

sample(target, 5)
  
  
target <- c("Aaron Nola", "Aaron Sanchez", "Bartolo Colon", "Brandon Finnegan", "Chris Sale", "Chris Tillman", "Corey Kluber", "Dan Straily", "Ian Kennedy", "J.A Happ", "Jake Odorizzi", "Jason Hammel", "Jose Fernandez", "Jose Quintana", "Julio Teheran", "Kevin Gausman", "Kyle Hendricks", "Matt Shoemaker", "Noah Syndergaard", "Tanner Roark", "Tyler Chatwood", "Zach Davies")

#With the code below, we find the mean of stats we could get from these players. 
finalrotation%>%
  filter(Player %in% (target))%>%
  summarise(salary = mean(Payrollsalary), ERA = mean(ERA), Wins = mean(ProjectedFull))
```
```{r}
# With the code below, we can generate a random 5 man rotation within the budget.

finalrotation%>%
  filter(Player %in% sample(target, 5))%>%
  summarise(salary = mean(Payrollsalary), ERA = mean(ERA), Wins = mean(ProjectedFull))

```  
  
```{r}  
# with the code below, we can check how the Angels' starting rotation pitched in 2016. 

pitchersalary%>%
  filter(Year == "2016" & Team == "LAA")%>%
  summarise(salary = mean(Payrollsalary), ERA = mean(ERA), Wins = mean(ProjectedFull))


```

```{r}
# With about similar money spent on each players, the Angels could have ended up with better quality pitchers with lower ERA and higher number of Wins brought to the team. The Angels and any other teams that have not spent money enough and efficiently may as well check on the list of players depending on their budget to create a possible optimal rotation which may make the team go to the playoffs. 

```